/* eslint-disable */
import "./globals.css";
import type { Metadata } from "next";

import { inter } from "@/assets/fonts/fonts";

export const metadata: Metadata = {
  title: "Факултет за музичка уметност Скопје",
  description: "Generated by create next app",
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white my-5`}>
   
          {props.children}
   
      </body>
    </html>
  );
}
